server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
  profiles:
    active:
      test
  #允许用户自定义的类覆盖系统提供的类
  main:
    allow-bean-definition-overriding: true
#日志
logging:
  #这种方法是使用xml的配置文件的形式配置，该xml配置文件规定了日志的格式，级别等信息
  config: classpath:logback.xml
  level:
    com.xdx.hello.spring.boot.dao: trace
mybatis:
  #xml文件存放位置
  mapper-locations: classpath*:/mapper/*.xml
  #实体类存放位置
  type-aliases-package: com.xdx.hello.spring.boot.entity
  #类型转换类的存放位置
  type-handlers-package: com.xdx.hello.spring.boot.handle
  configuration:
    #使用驼峰法
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: true
  page-size-zero: true
xdx:
    profiles:
      active: debug
